### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by samirkarimov** [ElvinMeherrembeyli/PragmatechFoundationProject#1]
https://github.com/ElvinMeherrembeyli/PragmatechFoundationProject/blob/79ca7c5d7ef94c3cba0a99d88b4b4e6c5176d047/index.html#L235

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />` 

bunu istifade etsen daha uygun olar. Cunku senin istifade elediyin eyni zamanda premium hissesine de tesir edir font awesomun ona gore problem yaradabiler

**Comment by ElvinMeherrembeyli** [comment]
Aradan Qaldirildi
