### ISSUE TITLE
Slider islemir

### ISSUE THREAD

**Issue by samirkarimov** [ElvinMeherrembeyli/PragmatechFoundationProject#10]
![elvin02](https://user-images.githubusercontent.com/24611841/103487556-cd490700-4e1f-11eb-8eae-37240b51af49.jpg)
Bu slider olmalidi amma islemir

**Comment by ElvinMeherrembeyli** [comment]
Bilirem menim kompumu satmiyaciyiq musteriye ama mende isdiyir)

4 Oca 2021 Pzt 00:00 tarihinde Samir Karimov <notifications@github.com>
şunu yazdı:

**Comment by samirkarimov** [comment]
upps isleyirmis sorry
