### ISSUE TITLE
pop up sekil problemi

### ISSUE THREAD

**Issue by samirkarimov** [ElvinMeherrembeyli/PragmatechFoundationProject#11]
![elvin03](https://user-images.githubusercontent.com/24611841/103487568-e18d0400-4e1f-11eb-8b32-fa0f08b433e4.jpg)
Pop up acilanda butun ekrani tutacaqsa bunu daha duzgun formada vermek lazimdir. genislik ve hundurluk nisbeti qorunmali ve pop up oldugu gorunmelidir

**Comment by ElvinMeherrembeyli** [comment]
burda pop up in yarisi sekil yarisida o sekil haqqinda meqale ve yaxudda melumat olacaq. nisbeti nece qorumaliyam onu anlamadim

**Comment by samirkarimov** [comment]
burdaki goruntude pop up yeni modal oldugu hissolunmur. butun divin olcusunu tam ekrandan bir az balaca ele ki modal oldugu bilinsin. Ve hansi metnleri yerlesdireceksese onu da yerlesdir yoxla cunku metnin olcusune gore dizaynda problem yasaya bilersen

**Comment by ElvinMeherrembeyli** [comment]
Hocam click edende ayri bir sehife acilmasindansa tam ekrani tutan bir modal olsun dedim. Metn lorem nen yoxlayaram

**Comment by samirkarimov** [comment]
fergi yoxdu yeni sehifede acilmasi modal da olabiler hec bir problem yoxdur sadece onun modal oldugunu musteriye hissetdirmek vacibdir
