### ISSUE TITLE
Events filter

### ISSUE THREAD

**Issue by samirkarimov** [ElvinMeherrembeyli/PragmatechFoundationProject#12]
![elvin04](https://user-images.githubusercontent.com/24611841/103487587-071a0d80-4e20-11eb-8913-8392808272f2.jpg)
Event filter islemir onu islek veziyyete getirmek lazimdir

**Comment by ElvinMeherrembeyli** [comment]
aradan qaldirildi

**Comment by samirkarimov** [comment]
harikasin
