### ISSUE TITLE
Qeydlər 

### ISSUE THREAD

**Issue by samirkarimov** [ElvinMeherrembeyli/PragmatechFoundationProject#3]
- CSS olaraq sistemli yazırsan
- Ortaq class məntigini araşdırsan ya da dərslərə baxsan çox daha sürətli yaza bilərsən
- Mütləq şəkildə bir gününü ayırıb CSS-dən SASS-a keçid etməlisən

Ümumi dəyərləndirmə 7/10 -dur

**Comment by ElvinMeherrembeyli** [comment]
Hocam dunen butun gunu css-den sass-a kecmeye calismisam. Ayri bir faylda
butun layiheni yeniden yaziram ama cssde oxumur.

6 Ara 2020 Paz 19:14 tarihinde Samir Karimov <notifications@github.com>
şunu yazdı:
