### ISSUE TITLE
Container>Row>Col mentigi

### ISSUE THREAD

**Issue by samirkarimov** [ElvinMeherrembeyli/PragmatechFoundationProject#3]
https://github.com/ElvinMeherrembeyli/PragmatechFoundationProject/blob/79ca7c5d7ef94c3cba0a99d88b4b4e6c5176d047/index.html#L180-L194

Sectionlari sistemli yazmisan onu beyendim amma diggetimi ceken container>row>col mentiginden istifade etmemisen.Bu mentigi istifade etsen cox daha suretli struktur cixardabilersen ortaya

**Comment by ElvinMeherrembeyli** [comment]
Bunu home page de yox soecial pagede tetbiq edecem
