### ISSUE TITLE
sass partial ve import

### ISSUE THREAD

**Issue by samirkarimov** [ElvinMeherrembeyli/PragmatechFoundationProject#4]
https://github.com/ElvinMeherrembeyli/PragmatechFoundationProject/blob/79ca7c5d7ef94c3cba0a99d88b4b4e6c5176d047/sass/style.scss#L1

burda fayllari import etmisen faylAdi.scss olaraq amma daha yaxsi olardi ki hansi fayli import edeceksense onun _faylAdi.scss olaraq adlandirib import edende de sadece @import 'faylAdi' formatinda import edesen bu daha sistemli olar

**Comment by ElvinMeherrembeyli** [comment]
Aradan Qaldirildi
