### ISSUE TITLE
Javascript adlandirma

### ISSUE THREAD

**Issue by samirkarimov** [ElvinMeherrembeyli/PragmatechFoundationProject#6]
https://github.com/ElvinMeherrembeyli/PragmatechFoundationProject/blob/79ca7c5d7ef94c3cba0a99d88b4b4e6c5176d047/js/slider.js#L7

javascriptde variable adi vererken sadece inglis herflerinden istifade et İ yerine I istifade et

**Comment by ElvinMeherrembeyli** [comment]
Aradan Qaldirildi
