### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by samirkarimov** [ElvinMeherrembeyli/PragmatechFoundationProject#8]
Slider islemir Elvin yoxsa mene mi ele geldi?

**Comment by ElvinMeherrembeyli** [comment]
dunenki dersde dedim axi Hocam buttonlar islemir bidene. Onuda indi derse baxiram izah etmisiz bugun yazmaga calisacam

**Comment by samirkarimov** [comment]
button istifade edirsense preventDefault() metodunu arasdir

**Comment by ElvinMeherrembeyli** [comment]
transform Translate X kimi elesem olmaz ?

**Comment by samirkarimov** [comment]
Olar men ona gore demedim preventDefault() button taginin uzerinde aftamatik gelen clickleme funksiyasini saxlayir .Bu normal hallarda problem yaradir

**Comment by ElvinMeherrembeyli** [comment]
Tamam Hocam arasdiraram. Hocam bide menim motivasiyam cox pis dusub. Onun nece fix ede bilerem ? onsuz Qizdirmada bir terefden tesir edir  dahada yox olur motivasiyam

**Comment by samirkarimov** [comment]
motivasiya dusmeyi bizim isde cox normaldir.Bunu artirmaq ucun musteri terefinden baxmaq lazimdir meseleye ki men bu isi bitirsem artig odenisli nese edebilerem. Yanvar sonuna geder cox ciddi vaxt ayirmaq lazimdir ki artig emeyinizin behresini goresiniz

**Comment by ElvinMeherrembeyli** [comment]
Slide hazirdi. Umumi layihe evvelden aglimda tutdugum her sey bitdi. indi teze seyler gelib beynime musteri razilassa onlari tetbiq elemek istiyirem. Issue-ni baglaya bilersiniz
