### ISSUE TITLE
Sekil qaynaq problemi

### ISSUE THREAD

**Issue by samirkarimov** [ElvinMeherrembeyli/PragmatechFoundationProject#9]
![elvin01](https://user-images.githubusercontent.com/24611841/103487543-b3a7bf80-4e1f-11eb-81d4-c7d4d8196edd.jpg)
Sekil qaynaqlari duzgun deyil

**Comment by ElvinMeherrembeyli** [comment]
Oralarda sekil yoxdu bosdu. Ozum bos saxlamisam

3 Oca 2021 Paz 23:59 tarihinde Samir Karimov <notifications@github.com>
şunu yazdı:

**Comment by samirkarimov** [comment]
Javascriptle yoxlamalisan ki eger sekil gaynagi yoxdursa onun oldugu div de gorunmesin

**Comment by ElvinMeherrembeyli** [comment]
hocam burda sabit 3 div olacaq deye JSnen dinamiklik vermemisem. JSnen esas Materials, Events ve Gallery bolmesinde islemisem

**Comment by samirkarimov** [comment]
daha sonra bazadan 3 yox bir dene sekil olsa onu nece gostereceksen dizaynda fikirlesmisen mi onu

**Comment by ElvinMeherrembeyli** [comment]
son elave olunan 3sekil olacaq orda deye dusunmusdum men

**Comment by samirkarimov** [comment]
ya men 2 sekil elave etmisemse? her terefli dusunmek lazimdir
